# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Page Deploy CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.PAGE_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "miranquil@gmail.com"
          git config --global user.name "Miranquil"
          npm install hexo-cli@4.3.0 -g
          npm install

      - name: Fetch Theme
        run: |
          git clone -b custom git@github.com:miranquil/hexo-theme-keep.git themes/keep
    
      - name: Deploy
        run: |
          hexo clean
          hexo deploy
